
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeWrapper from "./components/ThemeWrapper";
import MenuSideDrawer from "./components/MenuSideDrawer";
import { QueryClientProvider } from "../../providers/query-client-provider";
import { Toaster } from "sonner";
import NavbarNext from "./components/NavbarNext";


const noto = localFont({
  src: "./fonts/noto.ttf",
  variable: "--font-noto",
  weight: "100 900", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${noto.variable} antialiased`}
      >
        <QueryClientProvider>
          <ThemeWrapper>
            <Toaster richColors/>
            <NavbarNext/>
            {children}
          </ThemeWrapper>
        </QueryClientProvider>
      </body>
    </html>
  );
}
